In [1]:
import sklearn

In [2]:
sklearn.__version__

'1.3.0'

In [3]:
from sklearn.datasets import load_
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

In [5]:
iris = load_iris()

In [6]:
type(iris)

sklearn.utils._bunch.Bunch

In [8]:
iris['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [12]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [16]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [19]:
iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names)

In [20]:
iris_df['label'] = iris.target

In [22]:
iris_df.sample(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
118                7.7               2.6                6.9               2.3   
65                 6.7               3.1                4.4               1.4   
93                 5.0               2.3                3.3               1.0   

     label  
118      2  
65       1  
93       1

In [24]:
X_train,X_test,y_train,y_test = train_test_split(iris.data,
                                                         iris.target,
                                                         test_size=0.2,
                                                         random_state=11)

In [25]:
dt_clf = DecisionTreeClassifier(random_state=11)
dt_clf.fit(X_train,y_train)
pred = dt_clf.predict(X_test)

In [26]:
y_test,pred

(array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
        0, 1, 0, 0, 2, 1, 0, 1]),
 array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
        0, 1, 0, 0, 2, 1, 0, 1]))

In [27]:
from sklearn.metrics import accuracy_score

In [28]:
accuracy_score(y_test,pred)

0.9333333333333333

In [29]:
dt_clf = DecisionTreeClassifier(random_state=11)
dt_clf.fit(iris.data,iris.target)
pred = dt_clf.predict(iris.data)
accuracy_score(iris.target,pred)

1.0

In [30]:
from sklearn.model_selection import KFold
import numpy as np

In [32]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)
print('붓꽃 데이터 세트 크기 : ',iris.data.shape[0])

붓꽃 데이터 세트 크기 :  150


In [39]:
cv_accuracy= []
kfold = KFold(n_splits=5,shuffle=True,random_state=None)
n_iter = 0
for  train_index, test_index  in kfold.split(iris.data):
    X_train,X_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = np.round( accuracy_score(y_test,pred)  ,4)
    cv_accuracy.append(accuracy)
print('정확도:',cv_accuracy)
print('평균정확도:',np.mean(cv_accuracy))
# shuffle=False
# 정확도: [1.0, 0.9667, 0.8667, 0.9333, 0.7333]
# 평균정확도: 0.9
# shuffle=True
# 정확도: [0.9667, 0.9667, 0.9667, 0.9333, 0.9667]
# 평균정확도: 0.9600200000000001

정확도: [0.9667, 0.9667, 0.9667, 0.9333, 0.9667]
평균정확도: 0.9600200000000001


In [43]:
kfold = KFold(n_splits=3,shuffle=True)
# kfold.split(X)는 폴드 세트를 3번 반복할 때마다 달라지는 학습/테스트 용 데이터 로우 인덱스 번호 반환. 
n_iter =0
for train_index, test_index  in kfold.split(iris_df):
    n_iter += 1
    label_train= iris_df['label'].iloc[train_index]
    label_test= iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 label
1    36
2    34
0    30
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    20
2    16
1    14
Name: count, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 label
0    38
2    35
1    27
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    23
2    15
0    12
Name: count, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 label
1    37
0    32
2    31
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
2    19
0    18
1    13
Name: count, dtype: int64


In [44]:
from sklearn.model_selection import StratifiedKFold

In [46]:
kfold = StratifiedKFold(n_splits=3,shuffle=False)
# kfold.split(X)는 폴드 세트를 3번 반복할 때마다 달라지는 학습/테스트 용 데이터 로우 인덱스 번호 반환. 
n_iter =0
for train_index, test_index  in kfold.split(iris_df,iris_df['label']):
    n_iter += 1
    label_train= iris_df['label'].iloc[train_index]
    label_test= iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 label
2    34
0    33
1    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
1    17
2    16
Name: count, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 label
1    34
0    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
2    17
1    16
Name: count, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 label
0    34
1    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    17
2    17
0    16
Name: count, dtype: int64


In [47]:
cv_accuracy= []
kfold = StratifiedKFold(n_splits=5,shuffle=False, random_state=None)
n_iter = 0
for  train_index, test_index  in kfold.split(iris.data,iris.target):
    X_train,X_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = np.round( accuracy_score(y_test,pred)  ,4)
    cv_accuracy.append(accuracy)
print('정확도:',cv_accuracy)
print('평균정확도:',np.mean(cv_accuracy))
# shuffle=False
# 정확도: [1.0, 0.9667, 0.8667, 0.9333, 0.7333]
# 평균정확도: 0.9
# shuffle=True
# 정확도: [0.9667, 0.9667, 0.9667, 0.9333, 0.9667]
# 평균정확도: 0.9600200000000001

정확도: [0.9667, 0.9667, 0.9, 0.9667, 1.0]
평균정확도: 0.9600200000000001


In [48]:
from sklearn.model_selection import cross_val_score

In [52]:
iris = load_iris()
dt_clf =DecisionTreeClassifier(random_state=156)
score = cross_val_score(dt_clf,iris.data,iris.target,cv=3,scoring='accuracy')

In [53]:
score

array([0.98, 0.94, 0.98])

In [ ]:
DecisionTreeClassifier()

In [54]:
from sklearn.linear_model import LinearRegression

In [55]:
LinearRegression()

LinearRegression()

In [56]:
from sklearn.model_selection import GridSearchCV

In [65]:
iris = load_iris()
dtree = DecisionTreeClassifier()
grid_param = {
     'max_depth':[1,2,3,4],
     'min_samples_split':[2,3,4],
}
grid = GridSearchCV(estimator=dtree,
                            param_grid=grid_param,
                            cv=3,
                            refit=True )
X_train,X_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.2,random_state=121)
grid.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3, 4],
                         'min_samples_split': [2, 3, 4]})

In [66]:
scores_df = pd.DataFrame(grid.cv_results_)

In [67]:
scores_df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_max_depth', 'param_min_samples_split', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'mean_test_score', 'std_test_score', 'rank_test_score'],
      dtype='object')

In [68]:
scores_df[['params','mean_test_score','rank_test_score','split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  \
0   {'max_depth': 1, 'min_samples_split': 2}         0.700000   
1   {'max_depth': 1, 'min_samples_split': 3}         0.700000   
2   {'max_depth': 1, 'min_samples_split': 4}         0.700000   
3   {'max_depth': 2, 'min_samples_split': 2}         0.958333   
4   {'max_depth': 2, 'min_samples_split': 3}         0.958333   
5   {'max_depth': 2, 'min_samples_split': 4}         0.958333   
6   {'max_depth': 3, 'min_samples_split': 2}         0.975000   
7   {'max_depth': 3, 'min_samples_split': 3}         0.975000   
8   {'max_depth': 3, 'min_samples_split': 4}         0.975000   
9   {'max_depth': 4, 'min_samples_split': 2}         0.950000   
10  {'max_depth': 4, 'min_samples_split': 3}         0.950000   
11  {'max_depth': 4, 'min_samples_split': 4}         0.966667   

    rank_test_score  split0_test_score  split1_test_score  split2_test_score  
0                10              0.700                0.7              0.700  
1                10              0.700                0.7              0.700  
2                10              0.700                0.7              0.700  
3                 5              0.925                1.0              0.950  
4                 5              0.925                1.0              0.950  
5                 5              0.925                1.0              0.950  
6                 1              0.975                1.0              0.950  
7                 1              0.975                1.0              0.950  
8                 1              0.975                1.0              0.950  
9                 8              0.925                1.0              0.925  
10                8              0.925                1.0              0.925  
11                4              0.975                1.0              0.925

In [71]:
grid.best_score_

0.975

In [73]:
pred = grid.best_estimator_.predict(X_test)

In [74]:
accuracy_score(y_test,pred)

0.9666666666666667