In [1]:
# 레이블 인코딩 ,원핫인코딩

In [2]:
from sklearn.preprocessing import LabelEncoder

In [5]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
encoder.fit(items)
print(encoder.classes_)

['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [8]:
items_trans = encoder.transform(items)
items_trans

array([0, 1, 4, 5, 3, 3, 2, 2])

In [9]:
encoder.inverse_transform(items_trans)

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

In [10]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [11]:
items

['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [12]:
encoder = LabelEncoder()
encoder.fit(items)
items_trans = encoder.transform(items)

In [15]:
items_trans.reshape(-1, 1)

array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]])

In [23]:
oh_encoder = OneHotEncoder(sparse_output=False)
oh_encoder.fit(items_trans.reshape(-1, 1))

OneHotEncoder(sparse_output=False)

In [25]:
oh_encoder.transform(items_trans.reshape(-1, 1))

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [26]:
import pandas as pd

In [28]:
df = pd.DataFrame({'item':items})

In [31]:
pd.get_dummies(df,dtype=int)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

In [32]:
from sklearn.datasets import load_iris
import pandas as pd

In [33]:
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names)

In [34]:
iris_df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [35]:
iris_df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [36]:
iris_df.min()

sepal length (cm)    4.3
sepal width (cm)     2.0
petal length (cm)    1.0
petal width (cm)     0.1
dtype: float64

In [37]:
iris_df.max()

sepal length (cm)    7.9
sepal width (cm)     4.4
petal length (cm)    6.9
petal width (cm)     2.5
dtype: float64

In [38]:
from sklearn.preprocessing import StandardScaler

In [39]:
s_scaler = StandardScaler()
iris_df_s = s_scaler.fit_transform(iris_df)

In [45]:
iris_df_s.mean().round()

-0.0

In [46]:
iris_df_s.var()

1.0

In [47]:
iris_df_s.std()

1.0

In [48]:
from sklearn.preprocessing import MinMaxScaler

In [49]:
m_scaler = MinMaxScaler()
iris_df_m = m_scaler.fit_transform(iris_df)

In [50]:
iris_df_m.min()

0.0

In [51]:
iris_df_m.max()

1.0

In [52]:
iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [64]:
train = np.arange(0,11).reshape(-1,1)
test = np.arange(0,12).reshape(-1,1)

In [65]:
train

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [66]:
scaler_m = MinMaxScaler()
scaler_m.fit(train)

MinMaxScaler()

In [67]:
scaler_m.transform(train).reshape(-1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [68]:
scaler_m.transform(test).reshape(-1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1])

In [69]:
scaler_m.fit_transform(test).reshape(-1)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])